---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 2048

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[bigtop::default]